### ISSUE TITLE
Récupérer une adresse de moins de 3 mois

### ISSUE THREAD

**Issue by ThibautGery** [betagouv/api-particulier#15]
# Récupérer un justificatif de domicile de moins de 3 mois

L'objectif de document est lister les différentes options pour récupérer un justificatifs de moins de trois mois.
### Fournisseur d'accès internet
- Free
- Orange
- SFR
- Orange
### Fournisseur Energétique
- Direct Energie
- EDF
- Engie
### Agence immobilière
- Foncia
- Nexity
### Entrée

API Particulier proposerait trois façon d'entrer différemment :
- identifiant métier du fournisseur
- identité pivot (nom + prénom + lieu de naissance + date de naissance + code INSEE du lieu de naissance + code INSEE du pays de naissance)
- jeton [FranceConnect](https://doc.integ01.dev-franceconnect.fr)
### Sortie

L'API proposerait dans l'idéal, l'adresse formattée avec ses coordonnées GPS

N'hésitez à ajouter vos commentaires

**Comment by ppezziardi** [comment]
super
restons sur les 2 premières catégories, les agences ça ne marche pas.
quel serait le bénéfice pour ces producteurs ? que peut-on leur amener ?
