### ISSUE TITLE
Utiliser des tokens chiffrés

### ISSUE THREAD

**Issue by Flightan** [betagouv/api-particulier#41]
Pour ne plus stocker des tokens en clair, il faut pouvoir utiliser des tokens qui ont été chiffrés en base.

**Comment by pknoth** [comment]
avant de faire la PR, il faut encrypter les tokens en base. Le mieux serait de faire une tâche rake afin de garder les deux versions de token puis de supprimer la version en clair après déploiement de api-particulier.
