### ISSUE TITLE
Transférer le serveur sur une offre serveur dédié

### ISSUE THREAD

**Issue by Flightan** [betagouv/api-particulier#43]
Actuellement le service tourne sur une machine "cloud", les récentes failles Meltdown/Spectre permettraient d'accéder à des données confidentielles.

On peut utiliser les scripts Ansible sur le gitlab de l'incubateur pour migrer vers une offre serveur dédié.

**Comment by pknoth** [comment]
@Flightan La faille pourrait être corrigée par la mise à jour du kernel linux. Par cette action nous pourrions rester dans le cloud.
