### ISSUE TITLE
Gérer les limitations des appels sortants

### ISSUE THREAD

**Issue by Flightan** [betagouv/api-particulier#45]
La DGFIP bloque une IP après qu'elle ai effectué plus de 50 appels incorrects en 5 minutes.

On peut:
 - demander de white-lister nos IPs
 - mapper plusieurs adresses IPs sur l'interface réseau des serveurs applicatifs (voir Vince B.)

**Comment by pknoth** [comment]
après quelques recherches j'aboutis aux commandes qui ont l'air de fonctionner :
```
root@particulier-sandbox:~# iptables -t nat -o ens3 -A POSTROUTING -j SNAT --to-source 193.70.63.96 -m state --state NEW -m statistic --mode nth --every 2 --packet 0
root@particulier-sandbox:~# iptables -t nat -o ens3 -A POSTROUTING -j SNAT --to-source 137.74.27.126 -m state --state NEW -m statistic --mode nth --every 2 --packet 1
```

**Comment by pknoth** [comment]
donc deux actions :
- [] commander les ips failover
- [] créer les tâches ansible de configuration

**Comment by annemarie35** [comment]
remarques planification :
- combien d'Ips on commande ?

**Comment by pknoth** [comment]
A noter que le mode nth de statistics de iptables droperait des packets (seraient pas reroutés) avec l'exemple cidessus. Il faudra préférer utiliser random.

**Comment by pknoth** [comment]
le serveur est whitelisté auprès des serveurs de la CAF, il est nécessaire de whitelister les nouvelles IP afin de pouvoir requêter leur services
