### ISSUE TITLE
utiliser des scopes pour gérer les droits sur les données

### ISSUE THREAD

**Issue by pknoth** [betagouv/api-particulier#51]
Un accès API nous donne les droits d'accès aux données de la DGFIP et de la CNAF.

Limiter les droits d'accès aux données suivant deux scopes dgfip et cnaf. Ces scopes seront dans un premier temps sauvegardés en base avec les tokens.

**Comment by pknoth** [comment]
une idée d'intitulé pour les scopes @Flightan ?

**Comment by annemarie35** [comment]
jeu_de_donnees = sous-ensemble de scopes
suggestion :

dgfip_avis_imposition
cnaf_attestation_droits

**Comment by pknoth** [comment]
trouver une stratégie pour filtrer les données (qf)
