### ISSUE TITLE
Augmenter la capacité du throttling

### ISSUE THREAD

**Issue by annemarie35** [betagouv/api-particulier#54]
cf #44
Pour l'instant il est à 20, il faudrait réfléchir à une taille max et la documenter (attention au pic aglaé)

**Comment by pknoth** [comment]
@Flightan tu as un contact AGLAE pour savoir si ils ont une idée du pic de requêtes ?

**Comment by pknoth** [comment]
Toujours pas de réponse de la part de AGLAE, il faudrait les relancer
