### ISSUE TITLE
Typo sur adresse

### ISSUE THREAD

**Issue by stephane** [betagouv/api-particulier#65]
Est-ce « address » ou « adresse » ?

https://github.com/betagouv/api-particulier/blob/ee0cb7cd495b94aa6f8d96e98ab2e874ab99d769/api/impots/index.js#L23

**Comment by pknoth** [comment]
Est ce qu'on a des clients en production avec cette erreur de typo ?

**Comment by Flightan** [comment]
Aucun jeton ne possède ce scope donc à priori non.

**Comment by rdubigny** [comment]
Ce scope n'est plus utilisé, il faut supprimer le code associé.

**Comment by rdubigny** [comment]
le scope à été supprimé #131
