### ISSUE TITLE
Throng crée un worker de plus que la variable `nbWorkers`

### ISSUE THREAD

**Issue by Flightan** [betagouv/api-particulier#67]
Le process parent crée `nbWorkers` fils donc au final si on met `nbWorkers=4` on se retrouver avec 5 instances de node.

https://github.com/betagouv/api-particulier/blob/7230300da42a58421a6ae6f882260eabd3a62d07/bin/www#L14

**Comment by pknoth** [comment]
c'est pas le worker master qui gère les autres ? GO PM2 !

**Comment by pknoth** [comment]
cf #68
