### ISSUE TITLE
déporter l'auth vers la gateway

### ISSUE THREAD

**Issue by pknoth** [betagouv/api-particulier#73]
Récupérer l'auth sous forme de headers fourni par kong et api-particulier-auth

**Comment by pknoth** [comment]
ce serait bien de faire une review à 4 mains, il faut que je fix l'installation du plugin et les durées de certificat das ansible pour tester

**Comment by rdubigny** [comment]
il suffit de/il y a plus qu'a tester en dev en staging puis déployer en prod
