### ISSUE TITLE
Lier les différents logs générés par un Id de corrélation

### ISSUE THREAD

**Issue by Flightan** [betagouv/api-particulier#86]
Objectif: pouvoir lier les erreurs dans Kong et en erreur à un clientID.

On devrait utiliser/créer un plugin de Kong qui ajouter un champ "Id de corrélation" en header de requête, à utiliser par les logs applicatifs et logs en erreur.

**Comment by rdubigny** [comment]
Il faut être en mesure de fournir les logs de son passage sur api particulier à une date donnée, à quelqu'un qui le demande.
